'use client';
import {useState} from 'react';import {ArrowRight,Camera,CheckCircle2,Clock3,MapPin,Mic,Search,ShieldCheck,UploadCloud} from 'lucide-react';
export default function Home(){const[text,setText]=useState(''),[result,setResult]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[loading,setLoading]=useState(false),[q,setQ]=useState('');
async function solve(){if(!text.trim())return;setLoading(true);const r=await fetch('/api/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,location:'Citizen confirmation required'})});setResult(await r.json());setLoading(false)}
async function createCase(){if(!result?.problem)return;const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:result.problem.name,category:result.problem.category,priority:result.problem.priority,description:text,problemId:result.problem.id})});const c=await r.json();setCases(x=>[c,...x]);}
return <main><header><div className="brand"><b>N</b><span>NagrikOne<small>Citizen Resolution Platform</small></span></div><nav><a href="#home">Home</a><a href="#library">Problem Library</a><a href="#cases">My Cases</a><a href="/payment">Payments</a></nav></header>
<section id="home" className="hero"><div><label><ShieldCheck/> VERIFIED-FIRST RESOLUTION ENGINE</label><h1>Har problem ka <em>next step.</em></h1><p>Government, civic, company, consumer, banking, cyber, telecom aur daily-life problems — tell NagrikOne what happened.</p><div className="input"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Example: Mere area mein street light 5 din se band hai..."/><div className="tools"><span><button><Mic/></button><button><Camera/></button><button><UploadCloud/></button></span><button className="primary" onClick={solve}>{loading?'Understanding...':'Start Resolution'} <ArrowRight/></button></div></div><div className="trust">✓ Smart detection &nbsp; ✓ Evidence checklist &nbsp; ✓ Citizen approval</div></div><div className="city"><div className="orb">N</div><div className="tower a">GOVT</div><div className="tower b">CIVIC</div><div className="tower c">COMPANY</div><div className="tower d">SERVICES</div></div></section>
{result?.problem&&<section className="resolution"><div className="card"><label>RESOLUTION PLAN</label><h2>{result.problem.name}</h2><p className="quote">“{text}”</p><div className="route"><CheckCircle2/><div><small>Responsible route</small><b>{result.problem.route}</b></div></div><h3>Smart questions</h3>{(result.problem.questions as string[]).map((x:string,i:number)=><div className="q" key={x}><b>0{i+1}</b><span>{x}<small>Only relevant information will be requested.</small></span><button>Confirm</button></div>)}<div className="evidence"><b>Evidence needed</b><span>{(result.problem.evidence as string[]).join(' • ')}</span></div><button className="primary wide" onClick={createCase}>Create Resolution Draft <ArrowRight/></button><div className="safe"><ShieldCheck/> Prototype: no external complaint is submitted automatically.</div></div></section>}
<section id="cases" className="section"><label>MY RESOLUTION CENTER</label><h2>Cases that move forward.</h2>{cases.length===0?<p className="muted">Your newly created cases will appear here.</p>:<div className="grid">{cases.map(c=><article className="case" key={c.id}><small>{c.category}</small><h3>{c.title}</h3><p><Clock3/> {c.status}</p><span>{c.id}</span></article>)}</div>}</section>
<section id="library" className="section"><label>NOVA KNOWLEDGE LAYER</label><h2>Problem Library</h2><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search problem types..."/></div><div id="problem-list" className="grid">{['Pothole / damaged road','Street light not working','Garbage dumping','Bike / car service complaint','Refund not received','Government certificate','Online fraud / cyber scam','Mobile / internet problem','Banking / UPI dispute','Home appliance service'].filter(x=>x.toLowerCase().includes(q.toLowerCase())).map(x=><article className="case" key={x}><small>WORKFLOW</small><h3>{x}</h3><button onClick={()=>setText(x)}>Use workflow →</button></article>)}</div></section>
<footer><b>NagrikOne</b><span>One Citizen. One Platform. Every Problem.</span><small>Created by Jahid Tamboli • Prototype</small></footer></main>}
